"use client";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
type User = {id: string; name: string; email: string; role: string; active: boolean};
export default function UserAdmin() {
  const [users, setUsers] = useState<User[]>([]); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [role, setRole] = useState("ANALYST"); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { fetch("/api/users").then(async r => {const d = await r.json(); if (!r.ok) throw new Error(d.error); return d;}).then(d => setUsers(d.users)).catch(e => setError(e.message)); }, []);
  async function save(method: string, body: unknown) {
    setBusy(true); setError("");
    try {const r = await fetch("/api/users", {method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}); const d = await r.json(); if (!r.ok) throw new Error(d.error); setUsers(prev => [...prev.filter(u => u.id !== d.user.id), d.user]); setPassword("");} catch(e) {setError(e instanceof Error ? e.message : "Account update failed");} finally {setBusy(false);}
  }
  return <section className="space-y-4"><h1 className="text-2xl font-bold">Workspace accounts</h1><p>Administrators manage accounts. Managers create records and review other users’ work. Analysts read records and may respond to assigned sessions.</p>{error ? <p role="alert">{error}</p> : null}<form className="space-y-3 rounded border bg-white p-4" onSubmit={e => {e.preventDefault();void save("POST",{name,email,password,role,active:true});}}><h2 className="font-semibold">Create account</h2><input aria-label="Account name" required placeholder="Name" value={name} onChange={e => setName(e.target.value)}/><input aria-label="Account email" required type="email" placeholder="Email" value={email} onChange={e => setEmail(e.target.value)}/><input aria-label="Initial password" required type="password" minLength={16} placeholder="Initial password (16+ characters)" value={password} onChange={e => setPassword(e.target.value)}/><select aria-label="New account role" value={role} onChange={e => setRole(e.target.value)}>{["ANALYST","MANAGER","ADMIN"].map(r => <option key={r}>{r}</option>)}</select><Button type="submit" disabled={busy}>Create account</Button></form>{users.map(user => <div key={user.id} className="flex flex-wrap items-center gap-3 rounded border bg-white p-3"><span>{user.name} · {user.email}</span><select aria-label={`Role for ${user.email}`} disabled={busy} value={user.role} onChange={e => save("PUT",{...user,role:e.target.value})}>{["ANALYST","MANAGER","ADMIN"].map(r => <option key={r}>{r}</option>)}</select><Button disabled={busy} onClick={() => save("PUT",{...user,active:!user.active})}>{user.active ? "Disable account" : "Enable account"}</Button></div>)}</section>;
}
